/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Engine_Engine */

#ifndef _Included_Engine_Engine
#define _Included_Engine_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Engine_Engine
 * Method:    greeter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Engine_Engine_greeter
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
